[tasks.build]
workspace = false

[tasks.test]
workspace = false

[tasks.test-app]
workspace = false
env = { PATH="${CARGO_MAKE_WORKING_DIRECTORY}/target/debug;${PATH}", LD_LIBRARY_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/target/debug:${LD_LIBRARY_PATH}", RUST_LOG="trace" }
command = "dotnet"
args = [ "run", "--project", "wooting-analog-sdk-test" ]
dependencies = [ "build" ]

[tasks.gen-headers]

[tasks.verify-headers]