[tasks.gen-headers]

[tasks.verify-headers]

[tasks.build-release]
args = ["build", "--all-features", "--release",  "${@}"]

[tasks.build-updater]
command = "cargo"
args = ["build", "--release", "--manifest-path", "../wooting-analog-sdk-updater/Cargo.toml"]

[tasks.build-test-plugin]
command = "cargo"
args = ["build", "--release", "--manifest-path", "../wooting-analog-test-plugin/Cargo.toml"]

[tasks.cargo-build-virtual-kb]
command = "cargo"
args = ["build", "--release", "--manifest-path", "../wooting-analog-virtual-control/Cargo.toml"]

[tasks.build-virtual-kb]
dependencies = ["cargo-build-virtual-kb"]

[tasks.build-wooting-plugin]
command = "cargo"
args = ["build", "--release", "--manifest-path", "../wooting-analog-plugin/Cargo.toml"]

[tasks.win-installer]
dependencies = ["build-release", "build-updater", "build-test-plugin", "build-wooting-plugin"]
command = "cargo"
args = ["wix", "--nocapture", "--output", "../target/wix/${CARGO_MAKE_CRATE_FS_NAME}-${CARGO_MAKE_CRATE_VERSION}-${CARGO_MAKE_RUST_TARGET_ARCH}.msi"]

[tasks.build-deb]
dependencies = ["build-release", "build-test-plugin", "build-wooting-plugin"]
command = "cargo"
args = ["deb", "${@}"]