[package]
name = "analog-sdk-wrapper"
version = "0.1.0"
authors = ["simon-wh <simon.whyte.lb@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
libloading = "0.5.1"
analog-sdk-common = { path = "../analog-sdk-common"}

[lib]
crate-type = ["cdylib", "rlib"]