name: Test CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo make test-flow
